# Generated by Django 2.0.13 on 2019-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('rank', models.CharField(max_length=3)),
                ('due_chk', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('complete_chk', models.BooleanField(default=False)),
            ],
        ),
    ]
