# Generated by Django 2.0.13 on 2019-05-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190517_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='published_at',
        ),
    ]
