# Generated by Django 2.0.13 on 2019-05-17 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190517_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_at',
            new_name='updated_at',
        ),
    ]
