# Generated by Django 2.0.13 on 2019-05-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190517_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='마감기한'),
        ),
    ]
